include:
- fission.py
kind: ArchiveUploadSpec
name: fission-py-kNzD

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: onb-br-suitability-fn-40667b04-9b86-4fdb-a912-07d383bb5fbc
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://fission-py-kNzD
  environment:
    name: onb-br-suitability-env
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2023-01-05T18:25:16Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: onb-br-suitability-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 3
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 0
      hpaMetrics:
      - resource:
          name: cpu
          target:
            averageUtilization: 80
            type: Utilization
        type: Resource
    StrategyType: execution
  concurrency: 500
  environment:
    name: onb-br-suitability-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: onb-br-suitability-fn-40667b04-9b86-4fdb-a912-07d383bb5fbc
      namespace: default
  requestsPerPod: 10000
  resources: {}
