apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: 0441b36d-40a3-429d-8889-676f9549ccb5
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: suitability-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /suitability
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /suitability
