include:
- ./func/*
kind: ArchiveUploadSpec
name: func-FWN3

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: suitability-fn-e66e06a1-c938-4fdc-8bd8-699d34896e8b
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: suitability-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-FWN3
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-07-26T13:53:06Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: suitability-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 3
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 80
    StrategyType: execution
  concurrency: 500
  environment:
    name: suitability-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.create_suitability_profile
    packageref:
      name: suitability-fn-e66e06a1-c938-4fdc-8bd8-699d34896e8b
      namespace: default
  requestsPerPod: 1
  resources: {}
